Redux
EddyShimwa/book-store pull request #2
Opened 2023-01-24 15:29 UTC by EddyShimwa

### Highlights 

- Added Redux Toolkit 
- Structure my application files using a "feature folder" approach and use the [ducks pattern](https://github.com/erikras/ducks-modular-redux) for your Redux files. 
- I Defined action types for adding and removing a book and also for checking status in categories
- I also Configured the Redux Store.
- I checked linters
- I used the correct gitflow

2023-01-24 16:03 UTC, danmainah requested changes
Hi @EddyShimwa , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ No linter errors
✔️ Gitflow was correctly used
✔️  Good design


# Required Changes ♻️

- [ ] Kindly ensure your license link is functional currently its broken

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-01-24 16:03 UTC, danmainah commented on src/redux/configureStore.js
> +
- [ ] @EddyShimwa kindly remove the commented code, it's not good practice to have commented code in your codebase.
- [ ] Also remove the `import { Provider } from 'react-redux';` since the provider is not being used in the store, the best practise is to have imports that are being used in that particular file.

2023-01-24 16:03 UTC, danmainah commented on src/redux/books/books.js
> +const REMOVE_BOOK = 'REMOVE_BOOK';
- [ ] Kindly ensure your action types values follow the [ducks pattern](https://github.com/erikras/ducks-modular-redux)

2023-01-24 16:03 UTC, danmainah commented on src/redux/books/books.js
> +];
- [ ] Kindly ensure the initial state is an empty array this is a project requirement 
![image](https://user-images.githubusercontent.com/61408860/214341214-852a6230-1e92-47ce-ab2e-187a13f1d741.png)

2023-01-24 16:03 UTC, danmainah commented on src/redux/categories/categories.js
> +const CHECK_STATUS = 'CHECK_STATUS';
- [ ] Kindly ensure your action types values follow the [ducks pattern](https://github.com/erikras/ducks-modular-redux)

2023-01-24 16:03 UTC, danmainah commented on src/redux/categories/categories.js
> +};
- [ ] Kindly ensure the initial state is an empty array this is a project requirement 
![image](https://user-images.githubusercontent.com/61408860/214343593-92f5b994-f977-4c09-b7b6-06a7f47427de.png)

2023-01-24 16:03 UTC, danmainah commented on src/redux/categories/categories.js
> +// import { createReducer, createAction } from '@reduxjs/toolkit';
- [ ]  @EddyShimwa kindly remove the commented code, it's not good practice to have commented code in your codebase.

2023-01-24 16:03 UTC, danmainah commented on src/redux/books/books.js
> +// import { combineReducers } from 'redux';
- [ ] @EddyShimwa kindly remove the commented code, it's not good practice to have commented code in your codebase.

2023-01-24 16:52 UTC, Lucas-Masaba requested changes
# Hello @EddyShimwa  👋 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![almost-there](https://media.giphy.com/media/dEPGknRiEniec/giphy.gif)

 ## Highlights 🍾 
- Linter checks passing ✔️ 
- Made most changes as requested by the previous reviewer 👍 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions 💭 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏 💻 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Lucas-Masaba in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

- [x] Please clear the block of commented code you have in `App.js` such that your code looks clean 
![image](https://user-images.githubusercontent.com/45460192/214355147-3a10aab8-7144-48fd-8582-db5c6ebd3d67.png)

- [ ] I cannot add or remove a book from your website because you created actions in the redux store that you did not use in your components. Please make sure that a user is able to add and delete a book 👍

2023-01-24 19:17 UTC, EddyShimwa commented
Hey @Lucas-Masaba In this project requirements we are not asked to use redux in our components!!

2023-01-25 06:57 UTC, EddyShimwa commented
Hey @Lucas-Masaba I think this is not in the project requirements of day 1! I just wrote the reducer and actions for removing and adding the book and they are all set! kindly check! thank you!

2023-01-25 07:19 UTC, m05e5 approved these changes
**Hi @EddyShimwa 

You did great. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![CleverScornfulBuffalo-size_restricted](https://user-images.githubusercontent.com/37901469/208869296-5ca9f6cc-a1b5-48fd-bd59-78fd83b35471.gif)

## Highlights
✔️ Descriptive PR 
✔️ your linters are all ok

## Optional suggestions


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_**m05e5**_

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._**

2023-01-25 07:40 UTC, EddyShimwa commented
hey @m05e5 Which comments??

2023-01-25 07:51 UTC, m05e5 commented
Sorry my bad

2023-01-25 09:17 UTC, merged

2023-01-25 12:53 UTC, Lucas-Masaba commented
Sorry, @EddyShimwa  for the late reply. I see you have already merged this branch.  I am glad you already resolved your query